config/routes.rb
HasIssues::Engine.routes.draw do
  resources :issues do
    resources :comments
    resources :subscriptions
     member do
      put 'close'
      put 'reopen'
    end
  end
end

app/models/has_issues/application_record.rb
module HasIssues
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/has_issues/comment.rb
module HasIssues
  class Comment < ApplicationRecord
    belongs_to :issue
    belongs_to :creator, polymorphic: true
    belongs_to :editor, polymorphic: true

    validates_presence_of :creator, :on => :create
    validates_presence_of :editor, :on => :update
    validates_presence_of :issue
    validates_presence_of :body

    # validates_uniqueness_of :body,
    #  :scope => [:creator_type, :creator_id, :issue_id],
    #  :message => I18n.t('has_issues.comment.errors.double_posted')

    def is_modified?
      !editor.nil?
    end

    def is_latest?
      issue.comments.last == self
    end

  end
end

app/models/has_issues/issue.rb
module HasIssues
  class Issue < ApplicationRecord

    belongs_to :closer, polymorphic: true
    belongs_to :issuer, polymorphic: true
    belongs_to :issueable, polymorphic: true

    has_many :comments, dependent: :destroy
    has_many :subscriptions, dependent: :destroy

    validates_presence_of :issueable, :unless => :is_closed?
    validates_presence_of :issuer, :unless => :is_closed?

    accepts_nested_attributes_for :comments

    def ordered_comments(unfiltered = false)
      vc = unfiltered ? comments : filtered_comments
      case config.comment_order.to_sym
      when :l then vc.order('created_at DESC')
      when :e then vc.order('created_at ASC')
      else vc
      end
    end

    def is_closed?
      !closed_at.blank?
    end

    def close(user = nil)
      return false if is_closed?
      self.closed_at = Time.now
      self.closer = user
      save
    end

    def reopen
      return false unless is_closed? && !issueable.nil?
      self.closed_at = nil
      save
    end


  end
end

app/models/has_issues/subscription.rb
module HasIssues
  class Subscription < ApplicationRecord
    belongs_to :subscriber, polymorphic: true
    belongs_to :issue

    validates_presence_of :subscriber, :issue
    validates_uniqueness_of :issue_id, :scope => [:subscriber_type, :subscriber_id]

  end
end

app/controllers/has_issues/application_controller.rb
module HasIssues
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :set_user
    layout 'application'

    protected

    def set_user
      @user = HasIssues.current_user_proc.call(self)
    end

  end
end

app/controllers/has_issues/comments_controller.rb
require_dependency "has_issues/application_controller"

module HasIssues
  class CommentsController < ApplicationController
    before_action :set_issue
    before_action :set_comment, only: [:edit, :update, :destroy]


    # GET /comments/new
    def new
      @comment = @issue.comments.new
    end

    # GET /comments/1/edit
    def edit
    end

    # POST /comments
    def create
      @comment = Comment.new(comment_params)
      @comment.creator = @user

      respond_to do |format|
        if @comment.save
          @comment.issue.reopen if @comment.issue.is_closed?
          format.html { redirect_to @issue, notice: 'Comment was successfully created.' }
          format.js
        else
          format.html { render :new }
        end
      end
    end

    # PATCH/PUT /comments/1
    def update
      @comment.editor = @user

      respond_to do |format|
        if @comment.update(comment_params)
          format.html { redirect_to @issue, notice: 'Comment was successfully updated.' }
          format.js
        else
          format.html { render :edit }
        end
      end
    end

    # DELETE /comments/1
    def destroy
      @comment.destroy
      
      respond_to do |format|
        format.html { redirect_to @issue, notice: 'Comment was successfully removed.' }
        format.js
      end
  end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_issue
         @issue = Issue.find(params[:issue_id])
      end

      def set_comment
        @comment = Comment.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def comment_params
        params.require(:comment).permit(:issue_id, :creator_id, :creator_type, :editor_id, :editor_type, :body)
      end
  end
end

app/controllers/has_issues/issues_controller.rb
require_dependency "has_issues/application_controller"

module HasIssues
  class IssuesController < ApplicationController
    before_action :set_issueable
    before_action :set_issue, only: [:show, :edit, :update, :destroy, :close, :reopen]

    # GET /issues
    def index
      @issues = @issueable.blank? ? Issue.order(created_at: :desc) : @issueable.issues
    end

    # GET /issues/1
    def show
      @participants = @issue.comments.map{|c| c.creator }.uniq
    end

    # GET /issues/new
    def new
      @issue = Issue.new
      @issue.comments.new
    end

    def edit
    end

    # POST /issues
    def create
      @issue = Issue.new(issue_params)
      @issue.comments.first.creator = @user
      @issue.comments.first.issue = @issue
      @issue.issuer = @user
      @issue.issueable = @issueable

      if @issue.save
        redirect_to @issue, notice: 'Issue was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /issues/1
    def update
      if @issue.update(issue_params)
        redirect_to @issue, notice: 'Issue was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /issues/1
    def destroy
      @issue.destroy
      redirect_to issues_url, notice: 'Issue was successfully destroyed.'
    end

    # PUT /issues/1/close
    def close
      # security_transgression_unless @thread.can_be_edited_by?(@user)

      @issue.errors.add(:base, t('has_issues.thread.errors.already_closed')) \
        unless @issue.close(@user)

      # @show_all = true

      respond_to do |format|
        format.html { redirect_to [@issuebale, @issue] }
        format.js { render :show }
      end
    end
    
    # PUT /issues/1/reopen
    def reopen
      # security_transgression_unless @thread.can_be_edited_by?(@user)

      @issue.errors.add(:base, t('has_issues.thread.errors.not_closed')) \
        unless @issue.reopen

      # @show_all = true

      respond_to do |format|
        format.html { redirect_to [@issuebale, @issue] }
        format.js { render :show }
      end
    end


    private
      # Use callbacks to share common setup or constraints between actions.
      def set_issueable
        @issueable = []
        params.each do |name, value|
          if name =~ /(.+)_id$/
            @issueable.push($1.classify.constantize.find(value))
          end
        end
        @issueable = @issueable.last if @issueable.length >= 1
        nil
      end

      def set_issue
        @issue = Issue.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def issue_params
        params.require(:issue).permit(:title, :closed, :comments_attributes => [:body])
      end
  end
end

app/controllers/has_issues/subscriptions_controller.rb
require_dependency "has_issues/application_controller"

module HasIssues
  class SubscriptionsController < ApplicationController
    before_action :set_subscription, only: [:show, :edit, :update, :destroy]

    # GET /subscriptions
    def index
      @subscriptions = Subscription.all
    end

    # GET /subscriptions/1
    def show
    end

    # GET /subscriptions/new
    def new
      @subscription = Subscription.new
    end

    # GET /subscriptions/1/edit
    def edit
    end

    # POST /subscriptions
    def create
      @subscription = Subscription.new(subscription_params)

      if @subscription.save
        redirect_to @subscription, notice: 'Subscription was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /subscriptions/1
    def update
      if @subscription.update(subscription_params)
        redirect_to @subscription, notice: 'Subscription was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /subscriptions/1
    def destroy
      @subscription.destroy
      redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_subscription
        @subscription = Subscription.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def subscription_params
        params.require(:subscription).permit(:issue_id, :subscriber_id, :subscriber_type)
      end
  end
end

app/helpers/has_issues/application_helper.rb
module HasIssues
  module ApplicationHelper

    # Returns a dynamic path based on the provided parameters
    def issueable_issue_path(issueable, issue)
       issueable.blank? ? 
         eval("main_app.#{issue.issueable.class.name.downcase+'_' unless issue.issueable.blank?}has_issues_path#{'(' + issue.issueable.class.name.downcase + '_id: ' + issue.issueable.id.to_s + ')' unless issue.issueable.blank?}") + "/issues/#{issue.id.to_s}" : 
         url_for(issue)
     # eval("#{issueable.class.name.downcase+'_' unless issueable.blank?}has_issues_path#{'(' + issueable.class.name.downcase + '_id: ' + issueable.id.to_s + ')' unless issueable.blank?}") + "/issues/#{issue.id.to_s}"
    end
    
    def markdown(text)
      renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
      options = {
        autolink: true,
        no_intra_emphasis: true,
        fenced_code_blocks: true,
        lax_html_blocks: true,
        strikethrough: true,
        superscript: true,
        footnotes: false
      }
      Redcarpet::Markdown.new(renderer, options).render(text).html_safe
    end
    
  end
end

app/helpers/has_issues/comments_helper.rb
module HasIssues
  module CommentsHelper
  end
end

app/helpers/has_issues/issues_helper.rb
module HasIssues
  module IssuesHelper
  end
end

app/helpers/has_issues/subscriptions_helper.rb
module HasIssues
  module SubscriptionsHelper
  end
end

app/views/has_issues/issues/edit.html.erb
<%= simple_form_for(@issue) do |f| %>
    <%= f.error_notification %>

    <div class="panel panel-default">
      <div class="panel-heading">
        <%= f.input :title, label: false, hint: 'Title', input_html: {class: 'form-control'} %>
      </div>

    </div>

  <div class="actions">
    <%= f.submit 'Update', class: 'btn btn-success' %>
    <%= link_to 'Cancel', :back, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/has_issues/issues/index.html.erb
<% content_for :title do %>
  <%= @issueable.name + ' · ' + @issueable.class.name + ' · ' if !@issueable.blank? %>Issues
<% end %>

<div class="row">
  <div class="col-md-12">
<p id="notice"><%= notice %></p>

<h1>
  Issues
  <%= link_to 'New Issue', new_issue_path, class: 'btn btn-success pull-right' unless @issueable.blank? %>
</h1>

<table class="table table-hover" style="border: 1px solid #ddd;">
  <thead>
    <tr>
      <th colspan="4">text</th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= content_tag :span, '', class: "glyphicon #{issue.is_closed? ? 'glyphicon-ok-circle' : 'glyphicon-exclamation-sign'}", aria: {hidden: true} %></td>

        <td>
          <span style="font-size:16px; font-weight: 600;">
            <%= link_to issue.issueable.name, [main_app, issue.issueable], class: 'text-muted' if @issueable.blank? %>
            <%= link_to issue.title, issueable_issue_path(@issueable, issue) %>
          
          </span>
          <p class="small text-muted">opend on <%= issue.created_at.to_formatted_s(:long_ordinal) %> by <%= issue.issuer.name %></p>
        </td>
        <td>a</td>
        <td>
          <% if issue.comments.count >= 1 %>
            <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
            <%= content_tag :span, issue.comments.count, class: "small" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Back to issued object', [main_app, @issueable] unless @issueable.blank? %><%= ' | ' unless @issueable.blank? %> 
<%= link_to 'all issues', all_issues_path %> 
  </div>
</div>

app/views/has_issues/issues/new.html.erb
<% content_for :title do %>
  <%= @issueable.class.name + ' · ' if !@issueable.blank? %>Issues New
<% end %>

<h1>New Issue on <%= @issueable.name %></h1>

<%= simple_form_for(@issue) do |f| %>
    <%= f.error_notification %>

    <div class="panel panel-default">
      <div class="panel-heading">

        <%= f.input :title, label: false, input_html: {placeholder: "Title", class: 'form-control'} %>

      </div>

      <%= f.simple_fields_for :comments do |c| %>
        <div class="panel-body">
          <%= c.input :body, label: false, input_html: {placeholder: "Leave a comment.", class: 'col-xs-12', rows: '8', data: {provide: "markdown"}} %>
          <%= f.button :submit, class: 'btn btn-success btn-sm pull-right', style: 'margin-left: 5px;' %>
          <%= link_to 'Cancel', :back, class: 'btn btn-default btn-sm pull-right' %>
        </div>
      <% end %>
    </div>
<% end %>

app/views/has_issues/issues/show.html.erb
<% content_for :title do %>
  <%= @issue.title %> · <%= @issueable.name + ' · ' + @issueable.class.name + ' · ' if !@issueable.blank? %>Issues
<% end %>


<div class="row">
  <div class="col-md-12">
    <div class="page-header">
      <h1>
        <%= @issue.title %>
        <%= link_to 'New Issue', new_issue_path, class: 'btn btn-sm btn-success pull-right', style: 'margin-left: 5px;' unless @issueable.blank? %> 
        <%= link_to 'Edit', edit_issue_path(@issue), class: 'btn btn-sm btn-default pull-right' if @issue.issuer == @user %>
      </h1>
      
      <% if @issue.is_closed? %>
        <%= link_to reopen_issue_path(@issue), method: :put, class: "btn btn-success" do %>
          <span class="glyphicon glyphicon-ok-circle" aria-hidden="true"></span> 
          Closed
        <% end %>
      <% else %>
        <%= link_to close_issue_path(@issue), method: :put, class: "btn btn-success" do %>
          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span> 
          Open
        <% end %>
      <% end %>
      <span class="text-muted">
        <strong>
          <%= @issue.issuer.name %>
        </strong> opened this issue on 
        <%= @issue.created_at.to_formatted_s(:long_ordinal) %> · 
        <%= pluralize(@issue.comments.count, 'comment') %>
      </span>

    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-9">
    <div id="issue_comments">
      <%= render @issue.comments %>
    </div>

    <%= content_tag :div, id: 'closed' do %>
      <span class="glyphicon glyphicon-ban-circle" aria-hidden="true"></span> 
      <strong><%= @issue.closer.name %></strong> closed this 
      <%= distance_of_time_in_words(@issue.closed_at, Time.now) %> ago
    <% end if @issue.is_closed? %>
    
    <hr>

    <div class="panel panel-default">
      <%= simple_form_for [@issue, @issue.comments.new] do |f| %>
        <div class="panel-heading">
          <%= f.error_notification %>
          <%= f.hidden_field :issue_id %>
        </div>

        <div class="panel-body form-group">
          <%= f.input :body, label: false, input_html: {placeholder: "Leave a comment.", class: 'col-xs-12', rows: '8', data: {provide: "markdown"}} %>
          <%= f.button :submit, class: 'btn btn-success btn-sm pull-right' %>
        </div>
      <% end %>
    </div>
    <%= link_to 'Back to issues', issues_path %> | 
    <%= link_to 'Back to issued object',[main_app, @issueable] %>
    <br><br>
  </div>
  <div class="col-md-3 small">
    <h5>Assignees</h5>
    <br>

    <hr>
    <h5>Labels</h5>
    <br>

    <hr>
    <h5>Notifications</h5>
    Subscribe<br>
    You’re not receiving notifications from this thread.

    <hr>
    <h5><%= pluralize(@participants.count, 'participant') %></h5>
    <%= @participants.map(&:name).join(', ') %>

  </div>
</div>